// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxpwkbxnayawpiewuask.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cHdrYnhuYXlhd3BpZXd1YXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODc4OTcsImV4cCI6MjA3MzI2Mzg5N30.CI8Au-0T9EgQgkY4F8zqyJSiWuYmazYJ0Cvp-syxGQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});